//! The in-app manual: the same markdown `docs/book/` publishes, in a window
//! beside the model (invariant 12).
//!
//! The page text is compiled in (`crate::docs`, generated by this crate's build
//! script), so Help works on a broken or partial install and needs nothing
//! alongside the executable. Only *images* are read from disk — see
//! [`resolved_markdown`] — because embedding screenshots would put megabytes in
//! a binary whose startup time is a feature.
//!
//! Three things open a page: the `?` in an options panel's footer, `F1` over a
//! panel, and the toolbar's Help tile. A tooltip's "Learn more" link is the
//! fourth, and it is why [`request_page`] exists: a tooltip is drawn deep inside
//! a widget with no route back to [`HelpState`], so it parks the request in
//! egui's own per-frame store and the overlay picks it up. That is the same
//! shape as a `UiOutput` intent, one frame shorter.

use std::path::{Path, PathBuf};
use std::sync::{Arc, Mutex};

use egui_commonmark::{CommonMarkCache, CommonMarkViewer};

use crate::docs::{Page, PageText, TOC};
use crate::keys;
use crate::theme::size;

/// Where the Help window is and what it is showing.
///
/// Lives in `UiState` like every other piece of chrome state, and is edited in
/// place rather than travelling as an intent — opening a page changes nothing
/// outside the chrome.
#[derive(Debug, Clone, Default)]
pub struct HelpState {
    /// Whether the window is up. Also what egui's title-bar ✕ clears.
    pub open: bool,
    /// The page being read.
    pub page: Page,
    /// Pages visited, for the Back button. Bounded: a reader who has clicked
    /// through forty links wants the contents list, not thirty-nine Backs.
    history: Vec<Page>,
    /// Directory the manual's images live in, set once by `app`. `None` when the
    /// install has no docs folder, which renders every image as its alt text.
    pub docs_dir: Option<PathBuf>,
    /// egui_commonmark's parsed-page and image cache. Behind an `Arc<Mutex<_>>`
    /// because `UiState` is `Clone` (undo snapshots it) and the cache is not —
    /// and because sharing one cache across snapshots is right anyway: it is a
    /// cache of the *manual*, which no edit changes.
    cache: Option<Arc<Mutex<CommonMarkCache>>>,
    /// The current page's markdown with its image paths resolved, kept so the
    /// splice runs on navigation rather than every frame.
    resolved: Option<(Page, String)>,
    /// Set when the page changes: the reading pane scrolls back to the top on the
    /// next frame. Keeping the old offset lands the reader in the middle of a page
    /// they have not seen.
    scroll_to_top: Option<()>,
    /// How far the last-drawn page overhung its reading pane, in points, or zero
    /// if it fitted. A *measurement* written by [`draw`] each frame, in the same
    /// spirit as `UiState::chrome_insets`, and read by nothing at run time.
    ///
    /// It exists because the one thing that goes wrong here cannot be seen from
    /// outside: an overhang of a few points raises a horizontal scrollbar under
    /// the whole manual, and egui keeps the fact private. `tests/help_window_
    /// layout.rs` reads this to hold every prose page at zero.
    pub page_overflow: f32,
}

/// The deepest chain of links Back will walk before the reader is better served
/// by the contents list.
const MAX_HISTORY: usize = 32;

impl HelpState {
    /// Open the manual at its contents page (Help > Documentation).
    pub fn open_contents(&mut self) {
        self.open_page(Page::Index);
    }

    /// Open the manual at `page`, remembering where we were.
    pub fn open_page(&mut self, page: Page) {
        if self.open && self.page != page {
            self.history.push(self.page);
            if self.history.len() > MAX_HISTORY {
                self.history.remove(0);
            }
        }
        self.page = page;
        self.open = true;
        self.resolved = None;
        self.scroll_to_top = Some(());
    }

    fn go_back(&mut self) {
        if let Some(previous) = self.history.pop() {
            self.page = previous;
            self.resolved = None;
            self.scroll_to_top = Some(());
        }
    }

    fn navigate(&mut self, page: Page) {
        if page != self.page {
            self.history.push(self.page);
            if self.history.len() > MAX_HISTORY {
                self.history.remove(0);
            }
            self.page = page;
            self.resolved = None;
            self.scroll_to_top = Some(());
        }
    }
}

/// The options panel whose window sits at `layer`, as a manual page.
///
/// `app`'s F1 handler asks the egui context which layer is under the pointer and
/// hands the answer here rather than matching window ids itself: the ids are this
/// crate's, and `OptionPanel` is not public.
pub fn option_panel_at(layer: egui::LayerId) -> Option<Page> {
    crate::state::OptionPanel::ALL
        .into_iter()
        .find(|panel| layer.id == egui::Id::new(panel.window_id()))
        .map(crate::state::OptionPanel::help_page)
}

/// The manual page for a workspace — what F1 opens when the pointer is not over
/// an options panel.
pub fn workspace_help_page(mode: crate::state::WorkspaceMode) -> Page {
    match mode {
        crate::state::WorkspaceMode::ThreeD => Page::Viewport,
        crate::state::WorkspaceMode::Uv => Page::Uv,
        crate::state::WorkspaceMode::Texture => Page::Tex,
        crate::state::WorkspaceMode::Opt => Page::OptIndex,
    }
}

/// Ask for a manual page from somewhere that cannot reach [`HelpState`] — a
/// tooltip's link, drawn inside a widget several calls down.
///
/// Parked in egui's per-frame data and collected by [`take_requested`] at the top
/// of the next frame's overlay.
pub(crate) fn request_page(ctx: &egui::Context, page: Page) {
    ctx.data_mut(|data| data.insert_temp(request_id(), page));
}

/// Collect and clear a pending [`request_page`].
pub(crate) fn take_requested(ctx: &egui::Context) -> Option<Page> {
    ctx.data_mut(|data| data.remove_temp::<Page>(request_id()))
}

fn request_id() -> egui::Id {
    egui::Id::new("help_page_request")
}

/// Draw the Help window, if it is open.
///
/// A native `egui::Window` with the contents list in a nested side panel and the
/// page in the middle, so it is dragged, resized, collapsed and closed like every
/// other window in the chrome.
pub(crate) fn draw(ctx: &egui::Context, state: &mut HelpState, viewport: egui::Rect) {
    if !state.open {
        return;
    }

    let cache = state
        .cache
        .get_or_insert_with(|| Arc::new(Mutex::new(CommonMarkCache::default())))
        .clone();
    let Ok(mut cache) = cache.lock() else {
        // The cache is only ever locked here, on one thread; a poisoned mutex
        // means a panic already happened and Help is not what to fix.
        return;
    };

    // Resolve, then lift the page text *out* of the state for the duration of the
    // window: the closure below needs `&mut state` (the Back button, the scroll
    // flag), and a borrow of the text would hold the whole struct. Put back at the
    // end, so the splice still runs once per navigation rather than per frame.
    ensure_resolved(state);
    let resolved = state.resolved.take();
    let markdown = resolved.as_ref().map_or("", |(_, text)| text.as_str());
    let mut open = state.open;
    let mut navigate_to = None;
    let mut page_overflow = 0.0;

    // Register this page's own links so the viewer reports a click instead of
    // handing the href to the browser. Cleared and re-registered per page:
    // egui_commonmark matches hrefs by exact string, and two pages can spell the
    // same target differently ("uv.md" and "../uv.md").
    cache.link_hooks_clear();
    let locale = doc_locale();
    for (href, _) in state.page.text(&locale).links {
        cache.add_link_hook(*href);
    }

    egui::Window::new(keys::ui_help::TITLE)
        .id(egui::Id::new("help_window"))
        .open(&mut open)
        .resizable(true)
        .default_size(size::HELP_WINDOW_DEFAULT)
        .min_size(size::HELP_WINDOW_MIN)
        .constrain_to(viewport)
        // Persistent chrome, not a transient popup: skip egui's fade so an open
        // window never spins the on-demand redraw loop (invariant 6).
        .fade_in(false)
        .fade_out(false)
        .show(ctx, |ui| {
            // The same nested-`Panel` primitive the Outliner's own split uses, so
            // egui owns the divider and the two panes exactly as it does there.
            egui::Panel::left("help_toc")
                .resizable(false)
                .exact_size(size::HELP_TOC_WIDTH)
                .show(ui, |ui| {
                    navigate_to = draw_contents(ui, state.page);
                });

            egui::CentralPanel::default().show(ui, |ui| {
                draw_page_header(ui, state);
                ui.separator();
                // Our own `ScrollArea` around the stock `show`, rather than
                // egui_commonmark's `show_scrollable`: that one is `#[doc(hidden)]`
                // and its own docs call it buggy beyond the example app. This also
                // puts the scroll offset within reach, which is what lets a
                // navigation start the new page at the top.
                //
                // **Both** directions scroll, and that is load-bearing rather than
                // a convenience. `Resize` - what makes a `Window` resizable - grows
                // `desired_size` to the content's measured size every frame it is
                // not being dragged, and a `ScrollArea` with a direction *disabled*
                // reports the overflow in that direction as its own size rather
                // than absorbing it. So a page with a wide table stretched the Help
                // window the moment it was opened, left it stretched (the growth is
                // a `max`, so nothing ever shrinks it back), and pinned the resize
                // handle: egui refuses to let a drag shrink a window below what its
                // content needs. Every page of a different width moved the window.
                // With the direction enabled the overflow becomes a scrollbar and
                // the window stays the size the reader put it at.
                let scroll = egui::ScrollArea::both()
                    .id_salt("help_page")
                    .auto_shrink([false, false]);
                let scroll = match state.scroll_to_top.take() {
                    Some(()) => scroll.vertical_scroll_offset(0.0),
                    None => scroll,
                };

                // **The page's margin goes outside the scroll area, not inside
                // it.** It used to be a `Frame` around the markdown *within* the
                // viewport, and that put a horizontal scrollbar under every page
                // in the manual - the prose ones by a hair, the ones with a table
                // by a mile. This is the first of the two reasons; the wrap mode
                // set on the content below is the other.
                //
                // The reason is that `CommonMarkViewer` does not wrap against the
                // `Ui` it is handed. It wraps against the scroll viewport, so an
                // inner margin buys the text nothing: a paragraph still ran the
                // full width of the viewport, and the frame then added its two
                // margins around that, leaving the content exactly `2 x margin`
                // wider than the space it had. Every page overflowed by the same
                // sixteen points and every page got the bar.
                //
                // With the margin outside, the viewport *is* the wrap width and
                // prose fits it exactly. Horizontal scrolling stays enabled all
                // the same: it is what absorbs anything that still cannot wrap,
                // and absorbing it is what keeps it from stretching the window.
                //
                // **And the wrap width comes from the scroll area itself, not
                // from a measurement taken beside it.** egui rounds a `Ui`'s rect
                // to the display's *pixel* grid, so at any scale but 1.0 a point
                // is not a whole pixel and `available_width` out here and the
                // viewport in there disagree by a fraction of one. A fraction is
                // enough: egui raises the bar on any overflow at all, so the
                // manual came up with a scrollbar that had almost nothing to
                // scroll - on a 150% display, on the first frame, until a resize
                // happened to round the two the same way. `show_viewport` hands
                // over the width the scroll area actually laid out, which cannot
                // disagree with itself.
                let pane = egui::Frame::new()
                    .inner_margin(size::HELP_PAGE_MARGIN)
                    .show(ui, |ui| {
                        scroll.show_viewport(ui, |ui, viewport| {
                            let page_width = (viewport.width() - size::HELP_WRAP_SLACK).max(0.0);
                            // Enabling horizontal scrolling is what tells egui the
                            // content may be as wide as it likes, so the wrap width
                            // has to be put back by hand - otherwise every paragraph
                            // lays out on one line and the whole manual scrolls
                            // sideways.
                            ui.set_max_width(page_width);
                            // Whichever is smaller: a screenshot must not be blown
                            // up past the size it was taken at, and it must not be
                            // the thing that puts a horizontal scrollbar under a
                            // page either.
                            let image_width = size::HELP_IMAGE_MAX_WIDTH.min(page_width).max(1.0);
                            CommonMarkViewer::new()
                                .max_image_width(Some(image_width as usize))
                                .show(ui, &mut cache, markdown);
                        })
                    });
                let pane = pane.inner;
                page_overflow = (pane.content_size.x - pane.inner_rect.width()).max(0.0);
            });
        });

    // A link the viewer swallowed: find which page it named.
    for (href, page) in state.page.text(&locale).links {
        if cache.get_link_hook(href) == Some(true) {
            navigate_to = Some(*page);
        }
    }

    state.resolved = resolved;
    state.open = open;
    state.page_overflow = page_overflow;
    if let Some(page) = navigate_to {
        state.navigate(page);
    }
}

/// The contents list: `SUMMARY.md`, flattened and indented by depth.
fn draw_contents(ui: &mut egui::Ui, current: Page) -> Option<Page> {
    let mut clicked = None;
    egui::ScrollArea::vertical()
        .id_salt("help_toc_scroll")
        .auto_shrink([false, false])
        .show(ui, |ui| {
            for (depth, page) in TOC {
                // The indent is a left margin rather than an `add_space` inside a
                // `horizontal`, because the layout is what decides whether a label
                // wraps: egui extends text in a horizontal layout and wraps it in a
                // vertical one. A title too long for the contents column — "Opt:
                // the optimization workspace" is — extended past the panel it lives
                // in, and a `Window` grows to whatever its content measures, so one
                // over-long row widened the whole Help window.
                egui::Frame::new()
                    .inner_margin(egui::Margin {
                        left: (f32::from(depth) * size::HELP_TOC_INDENT) as i8,
                        ..egui::Margin::ZERO
                    })
                    .show(ui, |ui| {
                        // A row spans the column rather than hugging its title,
                        // so its hover and selection fill read as a list rather
                        // than as a row of loose labels - and so the whole width
                        // is clickable, which is what a reader aims at.
                        //
                        // `top_down_justified` and not `add_sized`: the latter
                        // lays the widget out centred, which would put every
                        // title in the middle of its row. This keeps the label
                        // left and stretches only the button behind it, and it
                        // stays a *vertical* layout, which is what lets a title
                        // too long for the column wrap instead of running past
                        // it - see the note above.
                        ui.with_layout(egui::Layout::top_down_justified(egui::Align::LEFT), |ui| {
                            if ui.selectable_label(page == current, page.title()).clicked() {
                                clicked = Some(page);
                            }
                        });
                    });
            }
        });
    clicked
}

/// Back button and page title above the reading pane.
fn draw_page_header(ui: &mut egui::Ui, state: &mut HelpState) {
    ui.horizontal(|ui| {
        let can_go_back = !state.history.is_empty();
        if ui
            .add_enabled(can_go_back, egui::Button::new("←"))
            .on_hover_text(keys::ui_help::BACK)
            .clicked()
        {
            state.go_back();
        }
        // Truncated, not extended: a heading is the one thing on this row that
        // has no natural width, and at the window's minimum size the longest page
        // title is wider than the reading pane. An extended one would push the
        // window out and then refuse to let it be dragged back in.
        ui.add(egui::Label::new(egui::RichText::new(state.page.title()).heading()).truncate());
    });
}

/// Make sure `state.resolved` holds the current page's markdown with its image
/// destinations resolved. Runs the splice once per navigation, not per frame.
fn ensure_resolved(state: &mut HelpState) {
    if state
        .resolved
        .as_ref()
        .is_none_or(|(page, _)| *page != state.page)
    {
        let locale = doc_locale();
        let text = state.page.text(&locale);
        let markdown = resolved_markdown(text, &locale, state.docs_dir.as_deref());
        state.resolved = Some((state.page, markdown));
    }
}

/// A page's markdown with every image destination rewritten.
///
/// An image that is on disk becomes an absolute `file://` URI, which is what
/// egui_extras' file loader serves. One that is not becomes its own alt text in
/// italics — the viewer would otherwise draw a bare warning glyph, because
/// egui_commonmark passes alt text to the hover tooltip rather than to the
/// image's own fallback.
///
/// The rewrite is a splice at byte ranges the build script recorded, so no
/// markdown is parsed at run time.
fn resolved_markdown(text: &PageText, locale: &str, docs_dir: Option<&Path>) -> String {
    if text.images.is_empty() {
        return text.markdown.to_owned();
    }

    let mut out = String::with_capacity(text.markdown.len());
    let mut cursor = 0;
    for image in text.images {
        // The recorded span covers the destination inside `![alt](dest)`. An
        // image that is present replaces just that; one that is not replaces the
        // whole construct, closing paren included, or the `)` would be left in
        // the prose.
        let on_disk = docs_dir
            .map(|dir| dir.join(locale).join(image.path))
            .filter(|path| path.is_file());

        let (replace_from, replace_to, replacement) = match on_disk {
            Some(path) => (
                image.start,
                image.end,
                format!("file://{}", path.to_string_lossy().replace('\\', "/")),
            ),
            None => {
                let opening = text.markdown[..image.start]
                    .rfind("![")
                    .unwrap_or(image.start);
                let closing = text.markdown[image.end..]
                    .find(')')
                    .map_or(image.end, |offset| image.end + offset + 1);
                (opening, closing, format!("*{}*", image.alt))
            }
        };

        // Spans come in source order, but a malformed one must not make the
        // splice walk backwards and panic on the slice.
        if replace_from < cursor || replace_to > text.markdown.len() {
            continue;
        }
        out.push_str(&text.markdown[cursor..replace_from]);
        out.push_str(&replacement);
        cursor = replace_to;
    }
    out.push_str(&text.markdown[cursor..]);
    out
}

/// The manual directory to read from, which is the language of the negotiated
/// locale. A regional tag reads the language's pages: `de-AT` and `de` are one
/// manual, even where they would be two catalogs.
fn doc_locale() -> String {
    review_localization::locale().language.as_str().to_owned()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::docs::ImageRef;

    #[test]
    fn a_page_without_images_is_passed_through() {
        let text = PageText {
            markdown: "# Title\n\nBody.\n",
            images: &[],
            links: &[],
        };
        assert_eq!(resolved_markdown(&text, "en", None), text.markdown);
    }

    /// With no docs folder — the case a broken install, or a `cargo run` from a
    /// checkout without one, lands in — the image must degrade to its alt text
    /// and leave no markdown syntax behind.
    #[test]
    fn a_missing_image_becomes_its_alt_text() {
        const MARKDOWN: &str = "Before ![The gizmo](images/gizmo.png) after.";
        const DEST: &str = "images/gizmo.png";
        // `PageText` holds `&'static` slices, matching the generated table, so
        // the fixture's images have to be a const rather than a local.
        const START: usize = 7 + "![The gizmo](".len();
        const IMAGES: &[ImageRef] = &[ImageRef {
            start: START,
            end: START + DEST.len(),
            path: DEST,
            alt: "The gizmo",
        }];
        assert_eq!(&MARKDOWN[START..START + DEST.len()], DEST);
        let text = PageText {
            markdown: MARKDOWN,
            images: IMAGES,
            links: &[],
        };
        let resolved = resolved_markdown(&text, "en", None);
        assert_eq!(resolved, "Before *The gizmo* after.");
        assert!(!resolved.contains("]("), "left markdown syntax behind");
    }

    #[test]
    fn every_page_resolves_without_a_docs_directory() {
        for page in Page::ALL {
            let resolved = resolved_markdown(page.text("en"), "en", None);
            assert!(
                !resolved.contains("](images/"),
                "{}: an unresolved image reference survived",
                page.id()
            );
        }
    }

    #[test]
    fn opening_a_page_records_history_and_back_returns() {
        let mut state = HelpState {
            open: true,
            page: Page::Index,
            ..HelpState::default()
        };
        state.open_page(Page::Keyboard);
        assert_eq!(state.page, Page::Keyboard);
        state.go_back();
        assert_eq!(state.page, Page::Index);
        // Nothing left to go back to; the button is disabled, but the call must
        // still be harmless.
        state.go_back();
        assert_eq!(state.page, Page::Index);
    }

    /// Opening the page already shown must not stack a history entry, or Back
    /// appears to do nothing on the first press.
    #[test]
    fn reopening_the_same_page_adds_no_history() {
        let mut state = HelpState {
            open: true,
            page: Page::Index,
            ..HelpState::default()
        };
        state.open_page(Page::Index);
        assert!(state.history.is_empty());
    }
}
