//! The one shader source and everything sokol-shdc generates from it.
//!
//! `review.glsl` is the single annotated-GLSL source for all 15 programs;
//! `scripts/gen-shaders.{sh,ps1}` turns it into the checked-in `generated/`
//! directory — the per-backend HLSL5 and MSL sources plus [`generated`], shdc's
//! reflection (bind slots, attribute locations, and a Rust struct per uniform
//! block and storage-buffer element). `build.rs` compiles this host's generated
//! sources to committed bytecode.
//!
//! What this module is *for*, beyond re-exporting: the generated structs are the
//! authority on layout, so every hand-written `#[repr(C)]` GPU struct asserts its
//! size against its generated twin. Invariant 11 already pinned each against a
//! hand-typed number; that catches a field added on one side of the Rust/HLSL
//! boundary, but not a number typed wrong in the first place. Pinning against
//! generated text closes that.

// The generated file carries its own inner attributes, so it is included as a
// module file rather than `include!`d.
//
// `clippy::all` is silenced for the same reason `vendor/sokol-rust` is `exclude`d
// from the workspace: this is machine-written code we do not own, and the lints it
// trips are upstream's style, not ours (today: shdc emits each shader's source as a
// multi-kilobyte `const [u8; N]`, which `large_const_arrays` wants as a `static`).
// Silencing the group rather than today's specific lint is deliberate — the file is
// regenerated by a tool, so chasing each new lint would only tempt someone to hand-
// edit the one file that must never be hand-edited.
#[allow(clippy::all)]
#[path = "generated/review.rs"]
pub(crate) mod generated;

#[cfg(test)]
mod tests {
    use super::generated;

    /// Every program built on `vs_main` must see the same vertex attribute
    /// locations, because they all draw the one `SceneVertex` layout: the mesh, the
    /// line overlays, the selection flash and the GTAO G-buffer share a vertex
    /// buffer and a pipeline input layout. shdc numbers attributes per program, so
    /// this pins all four against the literal locations `review.glsl` declares —
    /// a mismatch would mean one pipeline reading the vertex stream shifted.
    #[test]
    fn shared_vertex_attributes_agree_across_programs() {
        let expected = [0usize, 1, 2, 3, 4, 5];
        let mesh = [
            generated::ATTR_MESH_IN_POSITION,
            generated::ATTR_MESH_IN_NORMAL,
            generated::ATTR_MESH_IN_UV,
            generated::ATTR_MESH_IN_TANGENT,
            generated::ATTR_MESH_IN_COLOR,
            generated::ATTR_MESH_IN_DEFORM,
        ];
        let line = [
            generated::ATTR_LINE_IN_POSITION,
            generated::ATTR_LINE_IN_NORMAL,
            generated::ATTR_LINE_IN_UV,
            generated::ATTR_LINE_IN_TANGENT,
            generated::ATTR_LINE_IN_COLOR,
            generated::ATTR_LINE_IN_DEFORM,
        ];
        let selection = [
            generated::ATTR_SELECTION_IN_POSITION,
            generated::ATTR_SELECTION_IN_NORMAL,
            generated::ATTR_SELECTION_IN_UV,
            generated::ATTR_SELECTION_IN_TANGENT,
            generated::ATTR_SELECTION_IN_COLOR,
            generated::ATTR_SELECTION_IN_DEFORM,
        ];
        let gbuffer = [
            generated::ATTR_GTAO_GBUFFER_IN_POSITION,
            generated::ATTR_GTAO_GBUFFER_IN_NORMAL,
            generated::ATTR_GTAO_GBUFFER_IN_UV,
            generated::ATTR_GTAO_GBUFFER_IN_TANGENT,
            generated::ATTR_GTAO_GBUFFER_IN_COLOR,
            generated::ATTR_GTAO_GBUFFER_IN_DEFORM,
        ];
        assert_eq!(mesh, expected, "mesh");
        assert_eq!(line, expected, "line");
        assert_eq!(selection, expected, "selection");
        assert_eq!(gbuffer, expected, "gtao_gbuffer");
    }

    /// The view bind slots the scene pipelines share, pinned against the plan's
    /// register map. These are the numbers `sg::Bindings` is filled at, so one
    /// slipping would bind a texture to the wrong sampler slot rather than fail.
    #[test]
    fn scene_view_slots_match_the_register_plan() {
        assert_eq!(generated::VIEW_CHECKER_TEXTURE, 0);
        assert_eq!(generated::VIEW_IRRADIANCE_CUBE, 1);
        assert_eq!(generated::VIEW_PREFILTER_CUBE, 2);
        assert_eq!(generated::VIEW_BRDF_LUT, 3);
        assert_eq!(generated::VIEW_ENV_CUBE, 4);
        // The seven material slots, contiguous from 5.
        assert_eq!(generated::VIEW_BASE_COLOR_TEX, 5);
        assert_eq!(generated::VIEW_NORMAL_TEX, 6);
        assert_eq!(generated::VIEW_ROUGHNESS_TEX, 7);
        assert_eq!(generated::VIEW_METALLIC_TEX, 8);
        assert_eq!(generated::VIEW_AO_TEX, 9);
        assert_eq!(generated::VIEW_EMISSIVE_TEX, 10);
        assert_eq!(generated::VIEW_OPACITY_TEX, 11);
        // The vertex-stage deform storage buffers, contiguous from 12.
        assert_eq!(generated::VIEW_DEFORM_INFLUENCES, 12);
        assert_eq!(generated::VIEW_DEFORM_PALETTE, 13);
        assert_eq!(generated::VIEW_MORPH_DELTAS, 14);
        assert_eq!(generated::VIEW_MORPH_WEIGHTS, 15);
    }

    /// `SceneUniforms` is uploaded to both stages from one Rust value, so the two
    /// generated blocks must describe the same bytes. They are separate blocks only
    /// because a sokol uniform block belongs to exactly one stage.
    #[test]
    fn the_two_scene_uniform_blocks_are_the_same_layout() {
        assert_eq!(
            size_of::<generated::SceneVs>(),
            size_of::<generated::SceneFs>()
        );
        assert_eq!(generated::UB_SCENE_VS, 0);
        assert_eq!(generated::UB_SCENE_FS, 1);
        assert_eq!(generated::UB_MATERIAL, 2);
    }
}
