/* automatically generated by rust-bindgen 0.71.1 */

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct fire_psd {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct fire_psd_info {
    pub width: u32,
    pub height: u32,
    pub channels: u16,
    pub bits_per_channel: u16,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of fire_psd_info"][::std::mem::size_of::<fire_psd_info>() - 12usize];
    ["Alignment of fire_psd_info"][::std::mem::align_of::<fire_psd_info>() - 4usize];
    ["Offset of field: fire_psd_info::width"]
        [::std::mem::offset_of!(fire_psd_info, width) - 0usize];
    ["Offset of field: fire_psd_info::height"]
        [::std::mem::offset_of!(fire_psd_info, height) - 4usize];
    ["Offset of field: fire_psd_info::channels"]
        [::std::mem::offset_of!(fire_psd_info, channels) - 8usize];
    ["Offset of field: fire_psd_info::bits_per_channel"]
        [::std::mem::offset_of!(fire_psd_info, bits_per_channel) - 10usize];
};
unsafe extern "C" {
    pub fn fire_psd_open(bytes: *const u8, len: usize) -> *mut fire_psd;
}
unsafe extern "C" {
    pub fn fire_psd_info_get(
        doc: *const fire_psd,
        out_info: *mut fire_psd_info,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn fire_psd_read_merged_rgba8(
        doc: *const fire_psd,
        out_pixels: *mut u8,
        out_len: usize,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn fire_psd_icc_len(doc: *const fire_psd) -> usize;
}
unsafe extern "C" {
    pub fn fire_psd_icc_get(
        doc: *const fire_psd,
        out_icc: *mut u8,
        out_len: usize,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn fire_psd_free(doc: *mut fire_psd);
}
